name: flutter_application_newtten
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0-162.0.dev

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_analytics: ^12.0.4

  fl_chart: ^0.66.0
  image_picker: ^1.2.1
  firebase_storage: ^13.0.6
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/appICON.png"
  min_sdk_android: 21